Add devise
LeslieAine/blog-app1 pull request #10
Opened 2023-05-31 09:24 UTC by LeslieAine

In this PR, we add Devise gem to my application and use it for registration and login of users.

Accomplishments:

- Remove current_user method in ApplicationController.
- Enable registration of new user.
- Enable user login by a combination of email and password.
- Hashed passwords are stored in database.
- Ask for combination of email.
- Can reset password.
- Modify the views in devise for registration and login to match the wireframes.

2023-05-31 16:15 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @LeslieAine, and @ambrose-kibet👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- Good job with authentication. ✔️
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- No linter errors. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-31 16:15 UTC, thecodechaser commented on app/models/user.rb
>    validates :name, :photo, :bio, :postscounter, presence: true
- [ ] Please make sure the application asks for confirmation of email as requested in the project requirements.

2023-06-01 06:56 UTC, rloterh commented on app/models/user.rb
>    validates :name, :photo, :bio, :postscounter, presence: true
well resolved! ✔️

2023-06-01 07:02 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Leslie,  

Your project is complete! 🏁 Great job for nailing it right on the first attempt 🥇 There is nothing else to say other than... it's time to merge it 🍾 Congratulations!  🎉💯🌟 

## Highlights 🎯 
🎲  Good job on implementing recommended changes!

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

**You can also consider:**
Let's change the heading title Author to Authors as there're two contributors.
Implementing the above change(s) will make your ReadMe/repository stand out even better! 😉

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-01 07:44 UTC, merged

2023-06-01 07:46 UTC, LeslieAine commented
Thank you @rloterh and @thecodechaser for the time to review our code and leave suggestions. 👍🏽